"""src/synthetic.py - P2.9a: a synthetic LinkedIn Connections.csv for the public demo.

Replaces the Phase 0 archetype generator (superseded: its archetype skills only
inverted the generator's own mappings).

The output is a raw export in LinkedIn's format, so the demo enters the product
through the same path a user's upload does. Nothing in it is derived from a real
person: names and companies come from Faker, occupational titles from O*NET 30.3
job titles (CC BY 4.0, USDOL/ETA), ambiguous titles from fixed templates below.
The only link to the real network is aggregate shape, set in Spec.

What this module never does: write a classification, an uncertainty flag, or a
group. The needs-review share is measured by running the locked classifier over
this file (tools/measure_synthetic.py). If it misses the band, stratum_weights
is re-registered and re-run, at most twice. The classifier is not touched.

Run from the repo root:
    python -m src.synthetic
"""

from __future__ import annotations

import csv
import io
import random
from dataclasses import dataclass, field
from datetime import date, timedelta
from pathlib import Path
from typing import Callable

import pandas as pd
from faker import Faker   # build-time only (D-31)

OUTPUT_PATH = Path("data/synthetic/Connections.csv")
ONET_TITLES_CSV = Path("data/onet/job_titles.csv")
ONET_CODE_COL = "O*NET-SOC Code"
ONET_TITLE_COL = "Job Title"

HEADER = ["First Name", "Last Name", "URL", "Email Address",
          "Company", "Position", "Connected On"]
PREAMBLE = [
    "Notes:",
    '"Synthetic demo export generated by network-visualiser (P2.9a). Every name, '
    'company and title is invented; no row describes a real person."',
    "",
]
ANCHOR_DATE = date(2026, 9, 1)        # fixed, not today(), so output is reproducible
EXCLUDED_MAJORS = frozenset({"55"})   # military
MAX_DRAW_ATTEMPTS = 500

# --- ambiguous title templates -----------------------------------------------
SENIORITY_BASE = ["Director", "Associate Director", "Executive Director", "Managing Director",
                  "Partner", "Associate Partner", "Managing Partner", "Associate",
                  "Senior Associate", "Manager", "Senior Manager", "Vice President",
                  "Senior Vice President", "Principal", "Head of Department", "Group Head"]
SCOPE = ["", " - EMEA", " - UK", " - Europe", " - London", " (Interim)", " - Global"]
FOUNDER_BASE = ["Founder", "Co-Founder", "Founder & CEO", "Founder & Director", "Owner",
                "Self-employed", "Freelance", "Entrepreneur", "Building something new",
                "Stealth Startup", "Founding Team"]
FOUNDER_SUFFIX = ["", " | Hiring", " | Building in public", " @ {brand}"]
SUBJECTS = ["Economics", "Mathematics", "Law", "History", "Psychology", "Business",
            "Engineering", "Physics", "Chemistry", "English", "Geography", "Politics",
            "Computer Science", "Accounting and Finance", "Biology", "Sociology",
            "Philosophy", "Architecture", "Marketing", "Statistics"]
STUDENT_FORMS = ["{s} Student", "{s} Graduate", "MSc {s} Student"]
ASPIRING = ["Data Analyst", "Solicitor", "Investment Banker", "Software Engineer",
            "Actuary", "Teacher", "Product Manager", "Architect"]
STUDENT_BARE = ["Student", "Graduate", "Recent Graduate", "Open to work",
                "Seeking new opportunities", "Career break"]
VAGUE_BASE = ["Consultant", "Advisor", "Specialist", "Analyst", "Coordinator",
              "Executive", "Professional", "Team Member", "Associate Consultant", "Operations"]
VAGUE_SUFFIX = ["", " - EMEA", " - UK", " (Contract)", " | Open to work", " - Client Side"]
HATS = ["Speaker", "Mentor", "Advisor", "Investor", "Board Member", "Author", "Coach", "Volunteer"]
SENIORITY_PREFIX = ["Senior", "Lead", "Junior", "Principal"]

STRATA = ("occupational", "multi_hat", "seniority_only", "founder",
          "student_seeking", "vague", "blank")


class PoolExhausted(RuntimeError):
    """A stratum could not produce another unused title: widen its templates."""


@dataclass(frozen=True)
class Spec:
    """Every knob in one place, so each calibration run is one recorded object.

    stratum_weights is the only knob tuned against the needs-review band.
    Everything else is structural, set from the real network's aggregates
    (Day 19: 442 rows, 384 distinct titles, 0 blank, 19 groups).

    Registered v2 after D-42. The v1 weights targeted 41.4% needs review, a
    figure inflated by truncated batches cached as abstentions. The corrected
    rate is 29.0%, so the weights were re-derived against it; this replaces the
    registration rather than spending one of the two allowed re-tunings.

    Run 1 (weights v2) measured 34.2%: seniority_only abstained at 0.41 rather
    than the estimated 0.90, and occupational at 0.25 rather than 0.12. Run 2
    re-weights against those measured rates.
    """
    n_rows: int = 442
    seed: int = 42
    stratum_weights: dict = field(default_factory=lambda: {   # re-tuned, run 2 of 2 allowed
        "occupational": 0.80, "multi_hat": 0.08, "seniority_only": 0.06,
        "founder": 0.02, "student_seeking": 0.02, "vague": 0.02, "blank": 0.0,
    })
    distinct_titles: int = 384        # exact: repeats = non-blank rows - this
    eligible_groups: int = 21         # SOC major groups occupational titles draw from
    group_zipf_s: float = 3.0         # skew across those groups
    group_rank_shift: int = 4         # flattens the top ranks: a pure Zipf head is
                                      # far more dominant than a real network's
    prefix_rate: float = 0.15
    company_pool: int = 220
    blank_company_rate: float = 0.04  # company is not a classifier input (USE_COMPANY False)
    max_title_words: int = 4


@dataclass(frozen=True)
class Row:
    first: str
    last: str
    company: str
    position: str
    connected_on: date
    stratum: str               # generator metadata only: never written to the export
    source_major: str | None   # O*NET major a title was drawn from: dry-run proxy only


# --- pure core -----------------------------------------------------------------

def allocate(n: int, weights: dict) -> dict:
    """Exact per-stratum counts summing to n (largest remainder)."""
    if set(weights) != set(STRATA):
        raise ValueError(f"weights must cover exactly {STRATA}")
    total = sum(weights.values())
    raw = {k: n * w / total for k, w in weights.items()}
    counts = {k: int(v) for k, v in raw.items()}
    short = n - sum(counts.values())
    for k in sorted(STRATA, key=lambda k: (-(raw[k] - counts[k]), STRATA.index(k)))[:short]:
        counts[k] += 1
    return counts


def clean_onet_titles(jt: pd.DataFrame, max_words: int) -> pd.DataFrame:
    """O*NET job titles usable as a LinkedIn headline: short, no punctuation clutter."""
    df = pd.DataFrame({
        "title": jt[ONET_TITLE_COL].astype(str).str.strip(),
        "major": jt[ONET_CODE_COL].astype(str).str[:2],
    })
    ok = (
        ~df["major"].isin(EXCLUDED_MAJORS)
        & ~df["title"].str.contains(r"[,/()]", regex=True)
        & (df["title"].str.split().str.len() <= max_words)
    )
    return df[ok].drop_duplicates("title").sort_values(["major", "title"]).reset_index(drop=True)


class TitleSource:
    """Draws titles never used before in this export, one stratum at a time."""

    def __init__(self, titles: pd.DataFrame, spec: Spec, rng: random.Random, fake: Faker):
        self.rng, self.spec, self.fake = rng, spec, fake
        self.used: set[str] = set()
        majors = sorted(titles["major"].unique())
        rng.shuffle(majors)                       # which groups are big is seeded
        self.majors = majors[:spec.eligible_groups]
        self.weights = [1.0 / (r + 1 + spec.group_rank_shift) ** spec.group_zipf_s
                        for r in range(len(self.majors))]
        self.by_major = {m: titles.loc[titles["major"] == m, "title"].tolist() for m in self.majors}

    def _unused(self, make: Callable[[], tuple[str, str | None]], stratum: str) -> tuple[str, str | None]:
        for _ in range(MAX_DRAW_ATTEMPTS):
            title, major = make()
            if title not in self.used:
                self.used.add(title)
                return title, major
        raise PoolExhausted(stratum)

    def _occupation(self) -> tuple[str, str]:
        m = self.rng.choices(self.majors, weights=self.weights)[0]
        return self.rng.choice(self.by_major[m]), m

    def fresh(self, stratum: str) -> tuple[str, str | None]:
        r = self.rng
        if stratum == "occupational":
            def make():
                t, m = self._occupation()
                if r.random() < self.spec.prefix_rate and t.split()[0] not in SENIORITY_PREFIX:
                    t = f"{r.choice(SENIORITY_PREFIX)} {t}"
                return t, m
        elif stratum == "multi_hat":
            def make():
                t, m = self._occupation()
                return " | ".join([t, *r.sample(HATS, r.choice((1, 2)))]), m
        elif stratum == "seniority_only":
            def make():
                return r.choice(SENIORITY_BASE) + r.choice(SCOPE), None
        elif stratum == "founder":
            def make():
                suffix = r.choice(FOUNDER_SUFFIX).format(brand=f"{self.fake.last_name()} Labs")
                return r.choice(FOUNDER_BASE) + suffix, None
        elif stratum == "student_seeking":
            def make():
                roll = r.random()
                if roll < 0.6:
                    return r.choice(STUDENT_FORMS).format(s=r.choice(SUBJECTS)), None
                if roll < 0.8:
                    return f"Aspiring {r.choice(ASPIRING)}", None
                return r.choice(STUDENT_BARE), None
        elif stratum == "vague":
            def make():
                return r.choice(VAGUE_BASE) + r.choice(VAGUE_SUFFIX), None
        else:
            raise ValueError(stratum)
        return self._unused(make, stratum)


def name_key(first: str, last: str) -> str:
    """Case- and whitespace-insensitive full name, the collision test for P2.8c."""
    return " ".join(f"{first} {last}".split()).casefold()


def unique_names(n: int, fake: Faker) -> list[tuple[str, str]]:
    names, seen = [], set()
    while len(names) < n:
        first, last = fake.first_name(), fake.last_name()
        k = name_key(first, last)
        if k not in seen:
            seen.add(k)
            names.append((first, last))
    return names


def choose_repeats(strata: list[str], n_repeats: int, rng: random.Random) -> set[int]:
    """Rows that reuse an earlier title. Never a stratum's first row, never blank,
    so every repeat has something to copy and the distinct count is exact."""
    first_seen: set[str] = set()
    eligible = []
    for i, s in enumerate(strata):
        if s == "blank":
            continue
        if s in first_seen:
            eligible.append(i)
        first_seen.add(s)
    if not 0 <= n_repeats <= len(eligible):
        raise ValueError(f"cannot place {n_repeats} repeats in {len(eligible)} eligible rows")
    return set(rng.sample(eligible, n_repeats))


def generate(onet_titles: pd.DataFrame, spec: Spec = Spec()) -> list[Row]:
    """Deterministic for a given spec, O*NET file and pinned Faker version."""
    rng = random.Random(spec.seed)
    fake = Faker("en_GB")
    fake.seed_instance(spec.seed)

    source = TitleSource(clean_onet_titles(onet_titles, spec.max_title_words), spec, rng, fake)
    companies = list(dict.fromkeys(fake.company() for _ in range(spec.company_pool * 2)))[:spec.company_pool]
    company_w = [1.0 / (i + 1) ** 0.8 for i in range(len(companies))]

    strata = [s for s, c in allocate(spec.n_rows, spec.stratum_weights).items() for _ in range(c)]
    rng.shuffle(strata)
    nonblank = sum(1 for s in strata if s != "blank")
    repeats = choose_repeats(strata, nonblank - spec.distinct_titles, rng)
    names = unique_names(spec.n_rows, fake)

    rows: list[Row] = []
    earlier: dict[str, list[int]] = {}
    when = ANCHOR_DATE
    for i, ((first, last), stratum) in enumerate(zip(names, strata)):
        if stratum == "blank":
            position, major = "", None
        elif i in repeats:
            # copy a random earlier ROW, not title: common titles get commoner
            src = rows[rng.choice(earlier[stratum])]
            position, major = src.position, src.source_major
        else:
            position, major = source.fresh(stratum)
        earlier.setdefault(stratum, []).append(i)

        company = "" if rng.random() < spec.blank_company_rate else rng.choices(companies, company_w)[0]
        if not position and not company:   # linkedin.py drops such rows; keep n exact
            company = rng.choices(companies, company_w)[0]
        rows.append(Row(first, last, company, position, when, stratum, major))
        when -= timedelta(days=rng.randint(0, 14))   # newest first, like the export
    return rows


def render(rows: list[Row]) -> str:
    buf = io.StringIO()
    buf.write("\n".join(PREAMBLE) + "\n")
    w = csv.writer(buf, lineterminator="\n")
    w.writerow(HEADER)
    for r in rows:
        # URL and Email stay blank: an invented profile URL could be a real person's.
        w.writerow([r.first, r.last, "", "", r.company, r.position,
                    r.connected_on.strftime("%d %b %Y")])
    return buf.getvalue()


# --- glue ----------------------------------------------------------------------

def load_onet_titles(path: Path = ONET_TITLES_CSV) -> pd.DataFrame:
    return pd.read_csv(path, dtype=str)


def main() -> None:
    spec = Spec()
    rows = generate(load_onet_titles(), spec)
    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    with OUTPUT_PATH.open("w", encoding="utf-8", newline="") as f:   # BOM-free
        f.write(render(rows))
    nonblank = [r.position for r in rows if r.position]
    print(f"Wrote {len(rows)} rows -> {OUTPUT_PATH}")
    print(f"  strata:          {allocate(spec.n_rows, spec.stratum_weights)}")
    print(f"  distinct titles: {len(set(nonblank))} of {len(nonblank)} non-blank")
    print(f"  blank company:   {sum(1 for r in rows if not r.company)}")


if __name__ == "__main__":
    main()
